# Course-derived reference script
# English filename: 01_install_core_r_packages.R
# Original course path: see source_manifest.csv
# Role: dependency inventory
# Adaptations applied for the skill package:
# - Filename flattened and translated to English.
# - Interactive working-directory selection replaced with SC_WORK_DIR/getwd() when present.
# - Example-specific object names, thresholds, metadata columns, and local filenames still require review.
# - Prefer scripts/course_adapted/ for runnable project workflows.
####################################################
#######欢迎关注《叉叉滴同学的生信笔记》#########
#######欢迎关注《叉叉滴同学的生信笔记》#########
#######欢迎关注《叉叉滴同学的生信笔记》#########
####################################################
#选择镜像地址####
chooseBioCmirror()
chooseCRANmirror()
WORK_DIR <- Sys.getenv("SC_WORK_DIR", unset = getwd())
setwd(WORK_DIR)
#安装R包####
install.packages(c("remotes","RANN",
                   "RColorBrewer",
                   "cowplot","Seurat","SeuratObject",
                   "fitdistrplus",
                   "future",
                   "future.apply",
                   "ggplot2",
                   "ggrepel",
                   "ggridges",
                   "httr", 
                   "ica",
                   "irlba", 
                   "jsonlite", 
                   "leiden", 
                   "lmtest", 
                   "matrixStats", 
                   "miniUI", 
                   "patchwork", 
                   "pbapply", 
                   "plotly", 
                   "png", 
                   "progressr", 
                   "purrr", 
                   "RANN", 
                   "RColorBrewer", 
                   "Rcpp", 
                   "RcppAnnoy", 
                   "reticulate", 
                   "rlang", 
                   "ROCR", 
                   "Rtsne", 
                   "scales", 
                   "scattermore", 
                   "sctransform", 
                   "shiny", 
                   "spatstat.explore", 
                   "spatstat.geom", 
                   "tibble", 
                   "uwot", 
                   "RcppEigen", 
                   "RcppProgress",
                   "CCA",
                   "clustree",
                   "cowplot",
                   "aplot",
                   "circlize", 
                   "cowplot",
                   "data.table", 
                   "devtools", 
                   "doParallel", 
                   "doRNG", 
                   "dplyr", 
                   "ggfun", 
                   "gghalves", 
                   "ggplot2", 
                   "ggplotify", 
                   "ggridges", 
                   "ggsci", 
                   "irlba",
                   "magrittr", 
                   "Matrix", 
                   "msigdbr", 
                   "pagoda2", 
                   "plyr", 
                   "pointr", 
                   "purrr", 
                   "RcppML", 
                   "readr", 
                   "reshape2", 
                   "reticulate", 
                   "rlang", 
                   "RMTstat", "R.utils",
                   "RobustRankAggreg", 
                   "roxygen2", 
                   "stringr", 
                   "tibble", 
                   "tidyr", 
                   "tidyselect", 
                   "tidytree", 
                   "VAM",
                   "harmony",
                   "hdf5r",
                   "assertthat",
                   "randomcoloR",
                   "NMF",
                   "AnnoProbe","clustermole",
                   "fastDummies","qs","igraph","scCustomize","paletteer",
                   "miscTools","SCINA",
                   "phylogram"),force = TRUE,ask = F, update = F)
BiocManager::install(c("DOSE",
                       "clusterProfiler",
                       "enrichplot",
                       "org.Hs.eg.db",
                       "limma",
                       "edgeR",
                       "maftools",
                       "ComplexHeatmap",
                       "preprocessCore",
                       "DESeq2",
                       "TCGAbiolinks",
                       "sva",
                       "GenomicFeatures",
                       "GEOquery",
                       "affy",
                       "impute",
                       "affyPLM",
                       "annotate",
                       "affycoretools",
                       "graph","gcrma",
                       "CLL",
                       "AnnotationDbi",
                       "RColorBrewer",
                       "oligo",
                       "singscore",
                       "quantiseqr",
                       "GSVA",
                       "monocle",
                       "SCpubr",
                       "UCell",
                       "AUCell", 
                       "BiocParallel", 
                       "ComplexHeatmap", 
                       "decoupleR", 
                       "fgsea", 
                       "ggtree", 
                       "GSEABase", 
                       "GSVA", 
                       "Nebulosa", 
                       "scde", 
                       "singscore",
                       "SummarizedExperiment",
                       "viper",
                       "sparseMatrixStats",
                       "celldex",
                       "tricycle","GeneOverlap","TOAST",
                       "infercnv","metapod","bluster","scran","celda","glmGamPoi","SingleR",
                       "wk", "units", "s2", "classInt", "warp", "biglm", "sf", "spData", "slider", "ResidualMatrix", "speedglm", "spdep", "rsample", "pscl", "grr", "batchelor",
                       "scDblFinder"),force = TRUE,update = F,ask = F)
install.packages("monocle_xxdchange.tar.gz", repos = NULL, type = "source")
install.packages("openai.tar.gz", repos = NULL)
install.packages("xxdAIcelltype.tar.gz", repos = NULL)
####################################################
#######欢迎关注《叉叉滴同学的生信笔记》#########
#######欢迎关注《叉叉滴同学的生信笔记》#########
#######欢迎关注《叉叉滴同学的生信笔记》#########
####################################################